name: todo_app
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


 
  cupertino_icons: ^1.0.2
  riverpod: ^2.3.6
  firebase_core: ^2.15.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.6.1
  cloud_firestore: ^4.8.1
  google_fonts: ^5.1.0
  flutter_screenutil: ^5.7.0
  iconly: ^1.0.1
  hooks_riverpod: ^2.3.6
  flutter_vector_icons: ^2.0.0
  smooth_page_indicator: ^1.1.0
  lottie: ^2.4.0
  country_picker: ^2.0.20
  pinput: ^2.2.31
  riverpod_annotation: ^2.1.1
  riverpod_lint: ^1.3.2
  sqflite: ^2.2.8+4
  dynamic_color: ^1.6.6
  liquid_pull_to_refresh: ^3.0.1
  flutter_datetime_picker_plus: ^2.0.1
  flutter_local_notifications: ^15.1.0+1
  rxdart: ^0.27.7
  timezone: ^0.9.2
  mockito: ^5.4.2
  fake_async: ^1.3.1
  sqflite_common_ffi: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  riverpod_generator: ^2.2.3

flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/json/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
 